---
- runFlow: ../common/bootstrap.yaml
- openLink: cobalt://settings
- assertVisible:
    id: e2e-screen-settings__index
- tapOn:
    id: e2e-action-settings__index-search
- inputText: compose
- tapOn:
    id: e2e-action-settings__index-open-processing
- assertVisible:
    id: e2e-screen-settings__processing
