---
- runFlow: ../common/bootstrap.yaml
- openLink: cobalt://settings/licenses
- assertVisible:
    id: e2e-screen-settings__licenses
- tapOn:
    id: e2e-action-settings__licenses-open-app-license
- tapOn:
    id: e2e-action-settings__licenses-back
