---
- runFlow: ../common/bootstrap.yaml
- openLink: cobalt://settings/viewer
- assertVisible:
    id: e2e-screen-settings__viewer
- tapOn:
    id: e2e-action-settings__viewer-open-stretch
- tapOn:
    id: e2e-action-settings__viewer-open-colormap
