---
- runFlow: ../common/bootstrap.yaml
- openLink: cobalt://settings/about
- assertVisible:
    id: e2e-screen-settings__about
- tapOn:
    id: e2e-action-settings__about-restart-guide
- tapOn:
    id: e2e-action-settings__about-reset-all
